import = ["/home/ankit/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 13

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Control"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
args = ["/home/ankit/.config/myscripts/tmux_with_alacritty.sh"]
program = "/bin/bash"

[window]
opacity = 1.0
startup_mode = "Maximized"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 6
y = 1
